### PR TITLE
Checking for valid response on spam? and ham? methods

### PR DESCRIPTION
**Pull request by tinogomes**

### CODE REVIEW

**Comment by ysbaddaden** [comment]
Could you explain why you need this feature? Can an Akismet service respond with something else than "true" or "false"?

**Comment by tinogomes** [comment]
If you question about a ham, but akismet is "out of service" you will receive a false spam for a valid message, like:

ham?("valid comment") => false

Understand ;)

**Comment by ysbaddaden** [comment]
All right, I understand the problem :)

But doesn't akismet reply with a HTTP status error in that case (ie. something else than 200 OK)? Otherwise I expect Net::HTTP to raise errors if the HTTP request fails badly (like an Errno::ETIMEDOUT).

**Comment by tinogomes** [comment]
[Just say goodbye](https://www.youtube.com/watch?v=J9bEYHOeQ0o)

**Pull request closed without merging**
